### ISSUE TITLE
데이터 간 동일인 존재 여부 확인

### ISSUE THREAD

**Issue by gowun** [gowun/BladderCancer_AMC#1]
1. 케이스 번호가 같은지?
2. 전체 row가 완벽히 같은지?

**Comment by gowun** [comment]
Data to Pickle 추가 내용
1. 숫자열인 Gene Symbol 제거
2. drop_duplicate() 해서 중복열 제거

**Comment by kis0403** [comment]
> 1. 케이스 번호가 같은지?
> 2. 전체 row가 완벽히 같은지?

1. ab,ac,bc 모두 케이스번호가 같은 건은 없음
2. ab,ac,bc 모두 row가 같은 경우는 없음. 정규화된 데이터라서 소숫점 어느정도에서 반올림하면 일치 가능성은 있지만 어떤 방식으로 정규화 되었는지 알 수 없기 때문에 근거 부족. 추가로 c 데이터에서 동일한 row가 중복으로 들어간 경우 발견
